//! Integration tests: parse -> to_xml -> parse round-trip tests.
//!
//! Per-fixture round-trip tests are generated by `build.rs` from the XML files
//! in `crates/hpxml-core/tests/data/v{2,3,4,5}/`, so adding a fixture
//! automatically covers its round-trip. Files named `invalid.xml` are excluded.
//!
//! Serialized output is passed through [`common::normalize_xsi`] before
//! re-parsing (see that helper for why).
//!
//! Every test module below is gated on its version feature, so the whole
//! target is empty (and still compiles) with no version features enabled.

#![cfg(any(feature = "v2", feature = "v3", feature = "v4", feature = "v5"))]

#[macro_use]
mod common;

include!(concat!(env!("OUT_DIR"), "/fixture_roundtrip_tests.rs"));

/// Locks the premise behind [`common::normalize_xsi`]: the serializer
/// unconditionally emits `xmlns:xsi` on `xs:any` extension content, and the
/// parser faithfully records it, so struct equality needs the normalization.
///
/// If upstream xsd-parser stops emitting the declaration, this test fails:
/// delete the normalization helper and its callers, not this test.
/// See <https://github.com/Bergmann89/xsd-parser/issues/256>.
#[cfg(feature = "v4")]
#[test]
fn serializer_emits_xsi_on_any_extensions() {
    let bytes = fixture!("v4/openst-base.xml");
    let doc = hpxml_core::v4::parse(bytes).expect("failed to parse v4/openst-base.xml");
    let xml = hpxml_core::HpxmlSerialize::to_xml(&doc).expect("failed to serialize");
    let text = String::from_utf8_lossy(&xml);
    assert!(
        text.contains("xmlns:xsi"),
        "expected xmlns:xsi artifact in serialized openst-base.xml"
    );
}
