//! Integration tests: parse all fixture files per version.
//!
//! Test functions are auto-generated by `build.rs` from the XML files in
//! `crates/hpxml-core/tests/data/v{2,3,4,5}/`. Adding a new fixture file automatically creates
//! a new test; no manual updates needed. Files named `invalid.xml` are excluded.

include!(concat!(env!("OUT_DIR"), "/fixture_parse_tests.rs"));
